@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

  package "UserPrefs Storage" #F4F6F6 {
    Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
    Class JsonUserPrefsStorage
  }

  package "AddressBook Storage" #F4F6F6 {
    Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
    Class JsonAddressBookStorage
    Class JsonSerializableAddressBook
    Class JsonAdaptedPerson
    Class JsonAdaptedTag
  }

  package "ArchivedBook Storage" #F4F6F6 {
    Class "<<interface>>\nArchivedBookStorage" as ArchivedBookStorage
    Class JsonArchivedBookStorage
    Class JsonSerializableArchivedBook
  }

  Class "<<interface>>\nStorage" as Storage
  Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" ArchivedBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage
Storage -down-|> ArchivedBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonArchivedBookStorage .up.|> ArchivedBookStorage
JsonArchivedBookStorage ..> JsonSerializableArchivedBook
JsonSerializableArchivedBook --> "*" JsonAdaptedPerson

@enduml
